<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Task;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActive()
    {
        return $this->createQueryBuilder("task")
            ->andWhere("task.status = :status")
            ->setParameter("status", Task::statusMap()["Active"])
            ->andWhere("task.endTime IS NULL")
            ->orderBy("task.deadline", "ASC")
            ->orderBy("task.priority", "DESC")
            ->getQuery()
            ->execute();
    }
}
