root:
  path: /
  defaults: { _controller: "AppBundle:Default:index" }
  methods: GET
app_category:
    resource: "@AppBundle/Resources/config/routing/category.yml"
    prefix:   /category
app_task:
    resource: "@AppBundle/Resources/config/routing/task.yml"
    prefix:   /task
app_tag:
    resource: "@AppBundle/Resources/config/routing/tag.yml"
    prefix:   /tag
