AppBundle\Entity\Note:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\NoteRepository
    manyToOne:
        task:
            targetEntity: AppBundle\Entity\Task
            inversedBy: notes
            joinColumn:
                nullable: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
    lifecycleCallbacks: {  }
